###
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
    "nombre1":"Bryan",
    "nombre2":"Neftaly",
    "apellido1":"Sosa",
    "apellido2":"Robles",
    "username":"bsosa",
    "pass":"bsosa",
    "email":"bsosa@prueba.com",
    "efechac":"1998-05-11",
    "fechamod":"2021-07-19"
}
###
POST  http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "user":"bsosa",
    "pass": "bsosas"
}

###
GET http://localhost:8080/login/consulta HTTP/1.1

