###
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
    "nombre1":"Erick",
    "nombre2":"Daniel",
    "apellido1":"Sosa",
    "apellido2":"Lopez",
    "username":"dsosa",
    "pass":"dsosa",
    "email":"dsosa@prueba.com",
    "efechac":"1996-07-25",
    "fechamod":"2021-07-22"
}
###
POST  http://localhost:40000/login HTTP/1.1
Content-Type: application/json

{
    "user":"gposadas",
    "pass": "gposadas"
}

###
GET http://localhost:40000/login/consulta HTTP/1.1
